"""Independent, large-sample audit of the V2 action mask.

For every visited state of random legal trajectories, checks:

1. ``mask[0]`` (no-op) is always legal, so no state has zero legal actions.
2. decoding: action ``1 + k*d + p`` addresses demand ``d``, candidate ``p``.
3. mask == per-action scalar validator ``validate_te_action`` (69 checks).
4. every *masked* action, applied to a clone, is rejected and leaves routes,
   dwell, path age, previous-TE slot and the accepted counter unchanged.
5. every *legal* action, applied to a clone, is accepted, places the demand on
   the requested candidate, starts the dwell, and -- for protected classes --
   has projected gross bottleneck utilization <= 1.0 after the move.
6. no legal action routes over a failed link.
7. the mask is unchanged by computing it twice (no hidden state).

States are generated by a uniformly random legal policy (no-op with
probability ``p_noop``) on every evaluation scenario and on randomized
``random_day`` training episodes (which contain random failures and bursts).
"""

from __future__ import annotations

from collections import Counter
from typing import Any

import numpy as np

from mplssim.experiments.v2_factory import make_env_v2

CHECKS = ("noop_illegal", "decode_mismatch", "mask_validator_disagreement",
          "masked_action_accepted", "masked_action_side_effect",
          "legal_action_rejected", "legal_action_wrong_path", "legal_action_no_dwell",
          "protected_projection_violation", "legal_over_failed_link",
          "mask_not_idempotent", "independent_projection_violation",
          "independent_projection_mismatch", "ppo_illegal_probability_mass")

_STATE_ATTRS = ("current_path", "te_dwell_remaining", "path_age_steps", "previous_te_path")


def independent_gross_bottleneck(eng: Any, d: int, p: int) -> float:
    """Projected gross bottleneck of moving d to p, recomputed from scratch.

    Sums the full offered volume of every connected demand over the links of
    its (post-move) path, without using any engine projection helper.
    """
    gross = np.zeros(len(eng.capacity))
    for j in range(eng.n_demands):
        if eng.disconnected[j] and j != d:
            continue
        path = p if j == d else int(eng.current_path[j])
        for e in eng.topo.path_dlink_indices(eng.demands[j].candidate_paths[path]):
            gross[e] += float(eng.demand_offered[j])
    links = eng.topo.path_dlink_indices(eng.demands[d].candidate_paths[p])
    return float(max(gross[e] / eng.capacity[e] for e in links))


def audit_state(env: Any, counts: Counter, ppo_policy: Any = None) -> None:
    eng = env.eng
    mask = env.action_masks()
    counts["states"] += 1
    counts["actions_checked"] += len(mask)
    counts["legal_te_actions"] += int(mask[1:].sum())
    if not mask[0]:
        counts["noop_illegal"] += 1
    if not np.array_equal(mask, env.action_masks()):
        counts["mask_not_idempotent"] += 1
    if ppo_policy is not None:
        import torch
        obs_t, _ = ppo_policy.policy.obs_to_tensor(env._obs()[None, :])
        with torch.no_grad():
            dist = ppo_policy.policy.get_distribution(obs_t, action_masks=mask[None, :])
        probs = dist.distribution.probs.cpu().numpy()[0]
        counts["ppo_states_checked"] += 1
        if float(probs[~mask].sum()) != 0.0:
            counts["ppo_illegal_probability_mass"] += 1
    if eng.disconnected.any():
        counts["states_with_disconnected_demand"] += 1
    if not eng._dlink_up.all():
        counts["states_with_failed_link"] += 1
    k = env.k
    for a in range(1, len(mask)):
        d, p = divmod(a - 1, k)
        if not (0 <= d < env.n_demands and 0 <= p < k):
            counts["decode_mismatch"] += 1
            continue
        ok, _ = eng.validate_te_action(d, p)
        if ok != bool(mask[a]):
            counts["mask_validator_disagreement"] += 1
        clone = eng.fast_clone()
        before = {n: getattr(clone, n).copy() for n in _STATE_ATTRS}
        accepted_before = clone.accepted_te_changes
        rec = clone.apply_te_action(d, p)
        if not mask[a]:
            if rec["accepted"]:
                counts["masked_action_accepted"] += 1
            if (clone.accepted_te_changes != accepted_before or any(
                    not np.array_equal(before[n], getattr(clone, n)) for n in _STATE_ATTRS)):
                counts["masked_action_side_effect"] += 1
            continue
        if not rec["accepted"]:
            counts["legal_action_rejected"] += 1
            continue
        if int(clone.current_path[d]) != p:
            counts["legal_action_wrong_path"] += 1
        if int(clone.te_dwell_remaining[d]) != eng.cfg.minimum_te_dwell_steps:
            counts["legal_action_no_dwell"] += 1
        if not clone._dlink_up[clone._cand_links[d][p]].all():
            counts["legal_over_failed_link"] += 1
        if clone._protected[d]:
            counts["protected_legal_moves"] += 1
            indep = independent_gross_bottleneck(eng, d, p)
            if indep > eng.cfg.protected_projected_max_util + 1e-9:
                counts["independent_projection_violation"] += 1
            if abs(indep - eng.projected_gross_bottleneck(d, p)) > 1e-9:
                counts["independent_projection_mismatch"] += 1
            # Projected gross load after the move, from the pre-move telemetry.
            if eng.projected_gross_bottleneck(d, p) > eng.cfg.protected_projected_max_util:
                counts["protected_projection_violation"] += 1


def run_audit(episodes: list[tuple[str, int]], p_noop: float = 0.5,
              rng_seed: int = 0, ppo_policy: Any = None) -> Counter:
    counts: Counter = Counter()
    rng = np.random.default_rng(rng_seed)
    for scenario, seed in episodes:
        env = make_env_v2(scenario, root_seed=seed)
        env.reset(options={"episode_seed": seed})
        truncated = False
        while not truncated:
            audit_state(env, counts, ppo_policy)
            mask = env.action_masks()
            legal = np.flatnonzero(mask[1:]) + 1
            a = 0 if (rng.random() < p_noop or len(legal) == 0) else int(rng.choice(legal))
            _, _, _, truncated, info = env.step(a)
            counts["transitions"] += 1
            counts["accepted_moves"] += int(info["decoded_action"].get("accepted", False))
            counts["frr_changes"] += int(info["frr_changes"])
    return counts
